
public class ShowProcessDetails extends WizardPanel {
    
    /** Creates new form InitEmbedProcess */
    public ShowProcessDetails(String details) {
        super(details);
        initComponents();
    }
    
    
    public void setDisplayText(String text){
        embedLabel.setText(text);
    }
    
    public void addOutputLine(String line){
        outputTextArea.append(line+"\n");
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        embedLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        outputTextArea.setEditable(false);
        outputScrollPane.setViewportView(outputTextArea);

        add(outputScrollPane, java.awt.BorderLayout.CENTER);

        embedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        embedLabel.setText("Embedding Data In Image...");
        add(embedLabel, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

    public boolean doValidation() {
        return true;
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JLabel embedLabel;
    // End of variables declaration//GEN-END:variables
    
}
