
public class VerifyOptions extends WizardPanel {
    
    javax.swing.JTable choiceTable;
    /** Creates new form VerifyOptions */
    public VerifyOptions(String display) {
        super(display);
        initComponents();
        
    }
    
    public void showChosenOptions(EmbedExtractOptions eo){
        javax.swing.JScrollPane viewPane=null;
        if(choiceTable==null && viewPane==null) {
            choiceTable = new javax.swing.JTable(eo);
            viewPane = new javax.swing.JScrollPane(choiceTable);
            add(viewPane,java.awt.BorderLayout.CENTER);
        }else{
            choiceTable.setModel(eo);
        }        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        messageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        messageLabel.setText("Click next to start the embedding process");
        add(messageLabel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    public boolean doValidation() {
        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
    
}
