public abstract class WizardPanel extends javax.swing.JPanel implements java.awt.event.FocusListener
 {
    private javax.swing.JLabel wizardLabel = null;
    private String stepText = null;
    private java.awt.Component firstFocusable = null;
        /** Creates new form WizardPanel */
    public WizardPanel(String stepText)
 {       
        this.stepText = stepText;
        initComponents();
    }           
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()
 {	//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }	//GEN-END:initComponents

    public void focusGained(java.awt.event.FocusEvent focusEvent)
 {                
        //javax.swing.JOptionPane.showMessageDialog(this,"Gain");
        if( wizardLabel == null ) return;               
        wizardLabel.setFont(wizardLabel.getFont().deriveFont(java.awt.Font.BOLD));
        if( firstFocusable != null ) firstFocusable.requestFocus();
           
    }    
    
    public void focusLost(java.awt.event.FocusEvent focusEvent) {      
        //javax.swing.JOptionPane.showMessageDialog(this,"Loss");
        if( wizardLabel == null ) return;        
        wizardLabel.setFont(wizardLabel.getFont().deriveFont(java.awt.Font.PLAIN));        
    }    
    
    public abstract boolean doValidation();
    
    /** Getter for property wizardLabel.
     * @return Value of property wizardLabel.
     */
    public javax.swing.JLabel getWizardLabel() {
        return wizardLabel;
    }
    
    /** Setter for property wizardLabel.
     * @param wizardLabel New value of property wizardLabel.
     */
    public void setWizardLabel(javax.swing.JLabel wizardLabel)
 {
        this.wizardLabel = wizardLabel;
    }
    
    /** Getter for property stepText.
     * @return Value of property stepText.
     */
    public java.lang.String getStepText() {
        return stepText;
    }
    
    /** Setter for property stepText.
     * @param stepText New value of property stepText.
     */
    public void setStepText(java.lang.String stepText)
 {
        this.stepText = stepText;
    }
    
    /** Getter for property firstFocusable.
     * @return Value of property firstFocusable.
     */
    public java.awt.Component getFirstFocusable()
 {
        return firstFocusable;
    }
    
    /** Setter for property firstFocusable.
     * @param firstFocusable New value of property firstFocusable.
     */
    public void setFirstFocusable(java.awt.Component firstFocusable)
 {
        this.firstFocusable = firstFocusable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
}
